export const data = [
  {
    id: 1,
    movie_name: "Cutlet for Three (Ein Schnitzel für drei)",
    movie_genre: "Comedy",
    release_date: 2000,
    actor_firstname: "Maïly",
    actor_lastname: "Utton",
    avator:
      "https://robohash.org/recusandaelaboriosamid.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 2,
    movie_name: "Year and a Half in the Life of Metallica, A",
    movie_genre: "Documentary|Musical",
    release_date: 1963,
    actor_firstname: "Pò",
    actor_lastname: "Jacobsz",
    avator: "https://robohash.org/aliquamabdolorem.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 3,
    movie_name: "This Is Elvis",
    movie_genre: "Documentary|Drama|Musical",
    release_date: 2009,
    actor_firstname: "Åke",
    actor_lastname: "Norkett",
    avator: "https://robohash.org/velvoluptatemin.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 4,
    movie_name: "Desert Rats, The",
    movie_genre: "Drama|War",
    release_date: 1995,
    actor_firstname: "Clémence",
    actor_lastname: "Lebbern",
    avator:
      "https://robohash.org/ipsumdelectusrepellat.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 5,
    movie_name: "Herr Lehmann",
    movie_genre: "Comedy|Drama",
    release_date: 2010,
    actor_firstname: "Eléa",
    actor_lastname: "Jevon",
    avator: "https://robohash.org/veniamnihilut.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 6,
    movie_name: "Ward, The",
    movie_genre: "Horror|Thriller",
    release_date: 2008,
    actor_firstname: "Irène",
    actor_lastname: "Trevillion",
    avator: "https://robohash.org/sequiquiaut.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 7,
    movie_name: "Mantle",
    movie_genre: "Documentary",
    release_date: 2006,
    actor_firstname: "Léone",
    actor_lastname: "Farndale",
    avator: "https://robohash.org/eosomnisqui.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 8,
    movie_name: "Bridge of Dragons",
    movie_genre: "Action|Romance|Sci-Fi|Thriller",
    release_date: 2012,
    actor_firstname: "Marie-thérèse",
    actor_lastname: "Roskelley",
    avator: "https://robohash.org/etfugiateos.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 9,
    movie_name: "Killer's Kiss",
    movie_genre: "Crime|Film-Noir",
    release_date: 1992,
    actor_firstname: "Régine",
    actor_lastname: "Kerkham",
    avator: "https://robohash.org/quasaliasillum.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 10,
    movie_name: "Li'l Abner",
    movie_genre: "Comedy|Musical",
    release_date: 2006,
    actor_firstname: "Andrée",
    actor_lastname: "Attock",
    avator: "https://robohash.org/laboreveniamminima.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 11,
    movie_name: "Mr. Sardonicus",
    movie_genre: "Horror",
    release_date: 2009,
    actor_firstname: "Mélina",
    actor_lastname: "Duckwith",
    avator:
      "https://robohash.org/dignissimossuntvelit.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 12,
    movie_name:
      "Unintentional Kidnapping of Mrs. Elfriede Ott, The (Die Unabsichtliche Entführung der Frau Elfriede Ott)",
    movie_genre: "Comedy",
    release_date: 1991,
    actor_firstname: "Gaëlle",
    actor_lastname: "Penberthy",
    avator:
      "https://robohash.org/autconsequunturreprehenderit.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 13,
    movie_name: "De-Lovely",
    movie_genre: "Drama|Musical",
    release_date: 2010,
    actor_firstname: "Kévina",
    actor_lastname: "Astin",
    avator:
      "https://robohash.org/repellatdoloribuset.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 14,
    movie_name: "Case of You, A",
    movie_genre: "Comedy|Romance",
    release_date: 2009,
    actor_firstname: "Séverine",
    actor_lastname: "Lyddiard",
    avator: "https://robohash.org/quodarchitectovel.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 15,
    movie_name: "Batman: Year One",
    movie_genre: "Action|Animation|Crime",
    release_date: 2012,
    actor_firstname: "Kuí",
    actor_lastname: "Ells",
    avator: "https://robohash.org/etmodiut.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 16,
    movie_name: "Catfish in Black Bean Sauce",
    movie_genre: "Comedy|Drama",
    release_date: 1992,
    actor_firstname: "Anaëlle",
    actor_lastname: "Mabone",
    avator: "https://robohash.org/quasnemoipsa.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 17,
    movie_name: "Euphoria (Eyforiya)",
    movie_genre: "Drama|Romance",
    release_date: 2002,
    actor_firstname: "Andréa",
    actor_lastname: "Cahalan",
    avator:
      "https://robohash.org/laborumconsequaturnecessitatibus.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 18,
    movie_name: "Runner, The (Davandeh)",
    movie_genre: "Drama",
    release_date: 2011,
    actor_firstname: "Mélissandre",
    actor_lastname: "Binion",
    avator:
      "https://robohash.org/pariaturtemporibuset.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 19,
    movie_name: "Fall Time",
    movie_genre: "Drama",
    release_date: 1993,
    actor_firstname: "Nuó",
    actor_lastname: "Pittman",
    avator: "https://robohash.org/inventoreetatque.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 20,
    movie_name: "Long Good Friday, The",
    movie_genre: "Drama|Thriller",
    release_date: 1993,
    actor_firstname: "Adélaïde",
    actor_lastname: "McInulty",
    avator: "https://robohash.org/perferendisetquo.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 21,
    movie_name: "Meet Me in St. Louis",
    movie_genre: "Musical",
    release_date: 2004,
    actor_firstname: "Pò",
    actor_lastname: "Leaver",
    avator: "https://robohash.org/eaquiet.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 22,
    movie_name: "Missing in Action",
    movie_genre: "Action|War",
    release_date: 2009,
    actor_firstname: "Almérinda",
    actor_lastname: "Prettyman",
    avator: "https://robohash.org/sitattempore.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 23,
    movie_name: "Woman in the Window, The",
    movie_genre: "Crime|Film-Noir|Thriller",
    release_date: 2007,
    actor_firstname: "Garçon",
    actor_lastname: "Snowling",
    avator: "https://robohash.org/omnistemporeomnis.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 24,
    movie_name: "Best Man Down",
    movie_genre: "Drama",
    release_date: 2012,
    actor_firstname: "Dù",
    actor_lastname: "Tippett",
    avator: "https://robohash.org/exquoest.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 25,
    movie_name: "Jimi Hendrix",
    movie_genre: "Documentary",
    release_date: 1986,
    actor_firstname: "Josée",
    actor_lastname: "Burbidge",
    avator: "https://robohash.org/etundevoluptas.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 26,
    movie_name: "Unstoppable",
    movie_genre: "Action|Adventure|Comedy|Drama|Thriller",
    release_date: 2012,
    actor_firstname: "Pò",
    actor_lastname: "MacUchadair",
    avator: "https://robohash.org/autetrepellat.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 27,
    movie_name: "Captain America: The First Avenger",
    movie_genre: "Action|Adventure|Sci-Fi|Thriller|War",
    release_date: 2010,
    actor_firstname: "Kù",
    actor_lastname: "Craighall",
    avator: "https://robohash.org/velitestharum.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 28,
    movie_name: "Ben X",
    movie_genre: "Drama",
    release_date: 1998,
    actor_firstname: "Angèle",
    actor_lastname: "Cordobes",
    avator:
      "https://robohash.org/quiscommodiarchitecto.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 29,
    movie_name: "Little Mermaid: Ariel's Beginning, The",
    movie_genre: "Animation|Children|Fantasy",
    release_date: 2009,
    actor_firstname: "Intéressant",
    actor_lastname: "Matzke",
    avator: "https://robohash.org/beataemolestiaseos.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 30,
    movie_name: "Sand Sharks",
    movie_genre: "Comedy|Horror|Sci-Fi|Thriller",
    release_date: 1988,
    actor_firstname: "Geneviève",
    actor_lastname: "Amis",
    avator: "https://robohash.org/doloremautemvel.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 31,
    movie_name: "Fantastic Fear of Everything, A",
    movie_genre: "Comedy",
    release_date: 1996,
    actor_firstname: "Hélèna",
    actor_lastname: "Braganza",
    avator: "https://robohash.org/sunttemporatotam.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 32,
    movie_name: "Soldier Blue",
    movie_genre: "Western",
    release_date: 2001,
    actor_firstname: "Léonie",
    actor_lastname: "Jurs",
    avator:
      "https://robohash.org/teneturnihiltempora.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 33,
    movie_name: "Paan Singh Tomar",
    movie_genre: "Crime",
    release_date: 1995,
    actor_firstname: "Kévina",
    actor_lastname: "Benedicto",
    avator:
      "https://robohash.org/voluptatemharumnatus.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 34,
    movie_name: "Numb",
    movie_genre: "Comedy|Drama|Romance",
    release_date: 2008,
    actor_firstname: "Åke",
    actor_lastname: "Freeland",
    avator:
      "https://robohash.org/minusharumasperiores.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 35,
    movie_name: "Soylent Green",
    movie_genre: "Drama|Mystery|Sci-Fi|Thriller",
    release_date: 2010,
    actor_firstname: "Ruò",
    actor_lastname: "Mizzen",
    avator: "https://robohash.org/accusantiumutaut.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 36,
    movie_name: "Navigators, The",
    movie_genre: "Comedy|Drama",
    release_date: 1992,
    actor_firstname: "Annotée",
    actor_lastname: "Ackland",
    avator: "https://robohash.org/quivoluptatemquod.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 37,
    movie_name: "Manon",
    movie_genre: "Crime|Drama",
    release_date: 1986,
    actor_firstname: "Illustrée",
    actor_lastname: "Kesby",
    avator:
      "https://robohash.org/exercitationemexplicabovelit.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 38,
    movie_name: "Dogs of War, The",
    movie_genre: "Drama|War",
    release_date: 2012,
    actor_firstname: "Almérinda",
    actor_lastname: "Uzelli",
    avator: "https://robohash.org/ipsavoluptaseum.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 39,
    movie_name: "Officer Down",
    movie_genre: "Crime|Drama",
    release_date: 2006,
    actor_firstname: "Mégane",
    actor_lastname: "Reinert",
    avator:
      "https://robohash.org/reiciendisnumquamquo.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 40,
    movie_name: "Derailed",
    movie_genre: "Drama|Thriller",
    release_date: 1997,
    actor_firstname: "Léonore",
    actor_lastname: "Marzelli",
    avator:
      "https://robohash.org/etaspernaturmolestiae.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 41,
    movie_name: "Tavarataivas",
    movie_genre: "Documentary",
    release_date: 2009,
    actor_firstname: "Almérinda",
    actor_lastname: "Coster",
    avator:
      "https://robohash.org/quolaborummolestiae.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 42,
    movie_name: "Charade",
    movie_genre: "Comedy|Crime|Mystery|Romance|Thriller",
    release_date: 2007,
    actor_firstname: "Lén",
    actor_lastname: "Callendar",
    avator:
      "https://robohash.org/repudiandaesequiquis.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 43,
    movie_name: "Box of Moon Light",
    movie_genre: "Comedy|Drama",
    release_date: 1996,
    actor_firstname: "Lucrèce",
    actor_lastname: "McKeaney",
    avator: "https://robohash.org/saepeestcorporis.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 44,
    movie_name: "Return of Swamp Thing, The",
    movie_genre: "Comedy|Horror|Sci-Fi",
    release_date: 1990,
    actor_firstname: "Marie-josée",
    actor_lastname: "Vasilyonok",
    avator:
      "https://robohash.org/blanditiisvoluptatemfacere.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 45,
    movie_name: "Women Aren't Funny",
    movie_genre: "(no genres listed)",
    release_date: 2012,
    actor_firstname: "Cléopatre",
    actor_lastname: "Passe",
    avator: "https://robohash.org/pariatursintex.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 46,
    movie_name: "Stromboli",
    movie_genre: "Drama",
    release_date: 1995,
    actor_firstname: "Yú",
    actor_lastname: "Diggons",
    avator:
      "https://robohash.org/voluptatemcupiditateimpedit.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 47,
    movie_name: "Swedish Love Story, A (Kärlekshistoria, En)",
    movie_genre: "Drama|Romance",
    release_date: 2006,
    actor_firstname: "Liè",
    actor_lastname: "Rudiger",
    avator:
      "https://robohash.org/etreiciendisvoluptatem.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 48,
    movie_name: "Manual of Love 2 (Manuale d'amore (capitoli successivi))",
    movie_genre: "Comedy|Romance",
    release_date: 2007,
    actor_firstname: "Loïc",
    actor_lastname: "Algeo",
    avator: "https://robohash.org/ullamdictaesse.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 49,
    movie_name: "Stray Dogs (Sag-haye velgard)",
    movie_genre: "Drama",
    release_date: 2002,
    actor_firstname: "Publicité",
    actor_lastname: "Tradewell",
    avator: "https://robohash.org/officiisrerumad.png?size=500x500&set=set1",
    is_fav : false,
  },
  {
    id: 50,
    movie_name: "Big Game",
    movie_genre: "Action|Adventure",
    release_date: 2005,
    actor_firstname: "Maïwenn",
    actor_lastname: "Besson",
    avator:
      "https://robohash.org/temporesolutaeveniet.png?size=500x500&set=set1",
      is_fav : false,
  },
  {
    id: 51,
    movie_name: "Lawless",
    movie_genre: "Crime|Drama",
    release_date: 1997,
    actor_firstname: "Örjan",
    actor_lastname: "Folkes",
    avator: "https://robohash.org/aspernaturabea.png?size=500x500&set=set1",
  },
  {
    id: 52,
    movie_name: "Worth Winning",
    movie_genre: "Comedy",
    release_date: 1997,
    actor_firstname: "Célia",
    actor_lastname: "Lambeth",
    avator:
      "https://robohash.org/impeditsapienteveniam.png?size=500x500&set=set1",
  },
  {
    id: 53,
    movie_name: "Going Ape!",
    movie_genre: "Comedy",
    release_date: 1966,
    actor_firstname: "Estève",
    actor_lastname: "Swadon",
    avator: "https://robohash.org/quiaetut.png?size=500x500&set=set1",
  },
  {
    id: 54,
    movie_name: "No and Me (No et moi)",
    movie_genre: "Drama",
    release_date: 2007,
    actor_firstname: "Michèle",
    actor_lastname: "Whistance",
    avator: "https://robohash.org/aliasdoloreum.png?size=500x500&set=set1",
  },
  {
    id: 55,
    movie_name: "Underworld U.S.A.",
    movie_genre: "Crime|Drama",
    release_date: 2004,
    actor_firstname: "Réservés",
    actor_lastname: "Kondratenya",
    avator: "https://robohash.org/iustoquiarerum.png?size=500x500&set=set1",
  },
  {
    id: 56,
    movie_name: "Simpatico",
    movie_genre: "Comedy|Drama",
    release_date: 1986,
    actor_firstname: "Clémence",
    actor_lastname: "Bellenger",
    avator: "https://robohash.org/abplaceatdolores.png?size=500x500&set=set1",
  },
  {
    id: 57,
    movie_name: "Cheap Thrills",
    movie_genre: "Comedy|Thriller",
    release_date: 2011,
    actor_firstname: "Aloïs",
    actor_lastname: "Kermott",
    avator: "https://robohash.org/quiaaccusamusa.png?size=500x500&set=set1",
  },
  {
    id: 58,
    movie_name: "Cold Prey II (Fritt Vilt II)",
    movie_genre: "Horror",
    release_date: 1993,
    actor_firstname: "Vérane",
    actor_lastname: "Skerm",
    avator: "https://robohash.org/quisamolestiae.png?size=500x500&set=set1",
  },
  {
    id: 59,
    movie_name: "Delirium",
    movie_genre: "Adventure|Romance|Sci-Fi",
    release_date: 1990,
    actor_firstname: "Eléonore",
    actor_lastname: "Hutchence",
    avator: "https://robohash.org/essedictaaut.png?size=500x500&set=set1",
  },
  {
    id: 60,
    movie_name: "Crash",
    movie_genre: "Crime|Drama",
    release_date: 2007,
    actor_firstname: "Garçon",
    actor_lastname: "Otteridge",
    avator:
      "https://robohash.org/doloremqueculpacommodi.png?size=500x500&set=set1",
  },
  {
    id: 61,
    movie_name: "Light Gradient",
    movie_genre: "Drama|Mystery|Romance",
    release_date: 1990,
    actor_firstname: "Léonie",
    actor_lastname: "Schaumaker",
    avator:
      "https://robohash.org/laudantiumtemporased.png?size=500x500&set=set1",
  },
  {
    id: 62,
    movie_name: "Any Questions for Ben?",
    movie_genre: "Comedy|Drama",
    release_date: 2008,
    actor_firstname: "Noëlla",
    actor_lastname: "Blackmore",
    avator: "https://robohash.org/eiusveroaut.png?size=500x500&set=set1",
  },
  {
    id: 63,
    movie_name: "Paris Blues",
    movie_genre: "Drama|Romance",
    release_date: 2001,
    actor_firstname: "Léa",
    actor_lastname: "Vernazza",
    avator:
      "https://robohash.org/suscipitvoluptasillo.png?size=500x500&set=set1",
  },
  {
    id: 64,
    movie_name: "Zanjeer",
    movie_genre: "(no genres listed)",
    release_date: 2005,
    actor_firstname: "Hélèna",
    actor_lastname: "Coade",
    avator: "https://robohash.org/utculpamaxime.png?size=500x500&set=set1",
  },
  {
    id: 65,
    movie_name: "Goodbye, South, Goodbye (Nan guo zai jian, nan guo)",
    movie_genre: "Crime|Drama",
    release_date: 2004,
    actor_firstname: "Hélène",
    actor_lastname: "Been",
    avator: "https://robohash.org/adipiscietrerum.png?size=500x500&set=set1",
  },
  {
    id: 66,
    movie_name: "Blue Angel, The",
    movie_genre: "Drama|Musical",
    release_date: 2008,
    actor_firstname: "Marie-josée",
    actor_lastname: "McCallum",
    avator: "https://robohash.org/commodinihileum.png?size=500x500&set=set1",
  },
  {
    id: 67,
    movie_name: "Dark Woods (Villmark)",
    movie_genre: "Adventure|Horror|Mystery|Thriller",
    release_date: 1993,
    actor_firstname: "Marie-ève",
    actor_lastname: "Swynfen",
    avator: "https://robohash.org/utdolorefugiat.png?size=500x500&set=set1",
  },
  {
    id: 68,
    movie_name: "Men of Respect",
    movie_genre: "Crime|Drama|Thriller",
    release_date: 2001,
    actor_firstname: "Aurélie",
    actor_lastname: "Salery",
    avator: "https://robohash.org/modidoloremquia.png?size=500x500&set=set1",
  },
  {
    id: 69,
    movie_name: "Ride Beyond Vengeance",
    movie_genre: "Western",
    release_date: 2001,
    actor_firstname: "Néhémie",
    actor_lastname: "Broader",
    avator: "https://robohash.org/quiutratione.png?size=500x500&set=set1",
  },
  {
    id: 70,
    movie_name: "Women of the Night (Yoru no onnatachi)",
    movie_genre: "Drama",
    release_date: 1991,
    actor_firstname: "Jú",
    actor_lastname: "Misson",
    avator: "https://robohash.org/inquomolestiae.png?size=500x500&set=set1",
  },
  {
    id: 71,
    movie_name: "Lucy",
    movie_genre: "Action|Sci-Fi",
    release_date: 2006,
    actor_firstname: "Agnès",
    actor_lastname: "Blaxland",
    avator: "https://robohash.org/liberorerumvero.png?size=500x500&set=set1",
  },
  {
    id: 72,
    movie_name: "As it is in Heaven (Så som i himmelen)",
    movie_genre: "Drama|Musical|Romance",
    release_date: 2000,
    actor_firstname: "Märta",
    actor_lastname: "Weagener",
    avator: "https://robohash.org/natuseaexplicabo.png?size=500x500&set=set1",
  },
  {
    id: 73,
    movie_name: "Stoic",
    movie_genre: "Drama",
    release_date: 1998,
    actor_firstname: "Mahélie",
    actor_lastname: "Basham",
    avator:
      "https://robohash.org/architectoreiciendisofficiis.png?size=500x500&set=set1",
  },
  {
    id: 74,
    movie_name: "Kedma",
    movie_genre: "Drama|War",
    release_date: 1995,
    actor_firstname: "Gösta",
    actor_lastname: "Vell",
    avator: "https://robohash.org/iustosuntillo.png?size=500x500&set=set1",
  },
  {
    id: 75,
    movie_name: "Do We Really Need the Moon?",
    movie_genre: "Documentary",
    release_date: 1993,
    actor_firstname: "Estée",
    actor_lastname: "Eccleston",
    avator: "https://robohash.org/rerumcumaut.png?size=500x500&set=set1",
  },
  {
    id: 76,
    movie_name: "Flowers in the Attic",
    movie_genre: "Drama|Mystery|Thriller",
    release_date: 1994,
    actor_firstname: "Eléa",
    actor_lastname: "Eadmead",
    avator:
      "https://robohash.org/atqueexpeditaconsequuntur.png?size=500x500&set=set1",
  },
  {
    id: 77,
    movie_name: "Hand Gun",
    movie_genre: "Action|Crime|Drama|Thriller",
    release_date: 2008,
    actor_firstname: "Gaétane",
    actor_lastname: "Grog",
    avator:
      "https://robohash.org/quiserrorconsequuntur.png?size=500x500&set=set1",
  },
  {
    id: 78,
    movie_name: "Coco Chanel & Igor Stravinsky",
    movie_genre: "Drama|Romance",
    release_date: 2003,
    actor_firstname: "Annotée",
    actor_lastname: "Van den Oord",
    avator:
      "https://robohash.org/officiisillotempore.png?size=500x500&set=set1",
  },
  {
    id: 79,
    movie_name: "Die, Mommie, Die",
    movie_genre: "Comedy",
    release_date: 1987,
    actor_firstname: "Bénédicte",
    actor_lastname: "Bushaway",
    avator:
      "https://robohash.org/quiacupiditatedolorum.png?size=500x500&set=set1",
  },
  {
    id: 80,
    movie_name: "Cops and Robbersons",
    movie_genre: "Comedy",
    release_date: 2009,
    actor_firstname: "Bérangère",
    actor_lastname: "Badrock",
    avator: "https://robohash.org/esseestplaceat.png?size=500x500&set=set1",
  },
  {
    id: 81,
    movie_name: "Method to the Madness of Jerry Lewis",
    movie_genre: "Documentary",
    release_date: 1991,
    actor_firstname: "Torbjörn",
    actor_lastname: "Kinghorne",
    avator:
      "https://robohash.org/ablaborumtemporibus.png?size=500x500&set=set1",
  },
  {
    id: 82,
    movie_name: "Journey to the Center of the Earth",
    movie_genre: "Adventure|Children|Sci-Fi",
    release_date: 1995,
    actor_firstname: "Görel",
    actor_lastname: "Devin",
    avator:
      "https://robohash.org/nemodoloresvoluptates.png?size=500x500&set=set1",
  },
  {
    id: 83,
    movie_name:
      "Harlan: In the Shadow of Jew Suess (Harlan - Im Schatten von Jud Süss)",
    movie_genre: "Documentary",
    release_date: 2002,
    actor_firstname: "Annotés",
    actor_lastname: "Jerdan",
    avator:
      "https://robohash.org/inciduntdolorlaboriosam.png?size=500x500&set=set1",
  },
  {
    id: 84,
    movie_name: "Visitor Q (Bizita Q)",
    movie_genre: "Comedy|Drama|Horror",
    release_date: 1999,
    actor_firstname: "Maï",
    actor_lastname: "Arnout",
    avator: "https://robohash.org/sitsaepequas.png?size=500x500&set=set1",
  },
  {
    id: 85,
    movie_name: "Not Quite Hollywood: The Wild, Untold Story of Ozploitation!",
    movie_genre: "Documentary",
    release_date: 2005,
    actor_firstname: "Méryl",
    actor_lastname: "Domerque",
    avator: "https://robohash.org/omnisquisequi.png?size=500x500&set=set1",
  },
  {
    id: 86,
    movie_name: "On the Line",
    movie_genre: "Comedy|Romance",
    release_date: 2010,
    actor_firstname: "Françoise",
    actor_lastname: "Hague",
    avator:
      "https://robohash.org/utblanditiisarchitecto.png?size=500x500&set=set1",
  },
  {
    id: 87,
    movie_name: "Saved!",
    movie_genre: "Comedy|Drama",
    release_date: 1992,
    actor_firstname: "Clémentine",
    actor_lastname: "Romaynes",
    avator:
      "https://robohash.org/officiissimiliquerem.png?size=500x500&set=set1",
  },
  {
    id: 88,
    movie_name: "Love at Large",
    movie_genre: "Romance|Thriller",
    release_date: 1998,
    actor_firstname: "Aí",
    actor_lastname: "McConachie",
    avator:
      "https://robohash.org/laudantiumomnisiste.png?size=500x500&set=set1",
  },
  {
    id: 89,
    movie_name: "Wild Zero",
    movie_genre: "Action|Comedy|Horror|Romance|Sci-Fi",
    release_date: 2009,
    actor_firstname: "Léandre",
    actor_lastname: "Rowlinson",
    avator:
      "https://robohash.org/sequidebitisdoloribus.png?size=500x500&set=set1",
  },
  {
    id: 90,
    movie_name: "King of the Jungle",
    movie_genre: "Drama|Thriller",
    release_date: 2011,
    actor_firstname: "Maïwenn",
    actor_lastname: "Lodovichi",
    avator: "https://robohash.org/rerumaliassoluta.png?size=500x500&set=set1",
  },
  {
    id: 91,
    movie_name: "U.S. vs. John Lennon, The",
    movie_genre: "Documentary",
    release_date: 2007,
    actor_firstname: "Anaïs",
    actor_lastname: "Heinl",
    avator: "https://robohash.org/earecusandaeeos.png?size=500x500&set=set1",
  },
  {
    id: 92,
    movie_name: "Bag of Hammers, A",
    movie_genre: "Comedy|Drama",
    release_date: 2005,
    actor_firstname: "Mylène",
    actor_lastname: "Comazzo",
    avator: "https://robohash.org/errormagnamaut.png?size=500x500&set=set1",
  },
  {
    id: 93,
    movie_name: "A Kind of America 2",
    movie_genre: "Comedy",
    release_date: 2003,
    actor_firstname: "Cécile",
    actor_lastname: "Vasse",
    avator:
      "https://robohash.org/etdolorumblanditiis.png?size=500x500&set=set1",
  },
  {
    id: 94,
    movie_name: "Full Moon in Blue Water",
    movie_genre: "Drama",
    release_date: 1994,
    actor_firstname: "Anaé",
    actor_lastname: "Cowperthwaite",
    avator: "https://robohash.org/laboriosamnonatque.png?size=500x500&set=set1",
  },
  {
    id: 95,
    movie_name: "Family Business",
    movie_genre: "Comedy",
    release_date: 2007,
    actor_firstname: "Laurélie",
    actor_lastname: "Wilprecht",
    avator:
      "https://robohash.org/minusarchitectoipsam.png?size=500x500&set=set1",
  },
  {
    id: 96,
    movie_name: "Bone",
    movie_genre: "Comedy",
    release_date: 1994,
    actor_firstname: "Andréa",
    actor_lastname: "Van Leeuwen",
    avator:
      "https://robohash.org/eligendiaperiamquia.png?size=500x500&set=set1",
  },
  {
    id: 97,
    movie_name: "Gregory Crewdson: Brief Encounters",
    movie_genre: "Documentary|Drama",
    release_date: 1997,
    actor_firstname: "Adélaïde",
    actor_lastname: "Muckeen",
    avator: "https://robohash.org/doloremagnamipsa.png?size=500x500&set=set1",
  },
  {
    id: 98,
    movie_name: "Candles on Bay Street ",
    movie_genre: "Drama",
    release_date: 1992,
    actor_firstname: "Renée",
    actor_lastname: "Erbe",
    avator: "https://robohash.org/dictaadsequi.png?size=500x500&set=set1",
  },
  {
    id: 99,
    movie_name: "48 Shades",
    movie_genre: "Comedy|Drama",
    release_date: 1988,
    actor_firstname: "Loïs",
    actor_lastname: "Swanne",
    avator:
      "https://robohash.org/doloribusminimasequi.png?size=500x500&set=set1",
  },
  {
    id: 100,
    movie_name: "Delhi-6",
    movie_genre: "Comedy|Crime|Drama",
    release_date: 2008,
    actor_firstname: "Mà",
    actor_lastname: "Bidmead",
    avator: "https://robohash.org/eadoloret.png?size=500x500&set=set1",
  },
];
